### ISSUE TITLE
NPE if input file is relative path and in current directory

### ISSUE THREAD

**Issue by buske** [charite/jannovar#130]
Jannovar's path processing crashes if there is no directory component to the input file path. It throws an NPE when you attempt to process a VCF file that is in your CWD, unless you specify it as an absolute path.

We're using the github v0.12 binary.

Jannovar works fine if you run it on the example VCF:
```
$ java -jar jannovar-cli-0.12.jar annotate data/hg19_refseq.ser examples/small.vcf 
Options
verbosity: 1
dataFile: data/hg19_refseq.ser
vcfFilePaths: [examples/small.vcf]
chromosomalChanges: []
showAll: false
jannovarFormat: false
writeJannovarInfoFields: false
writeVCFAnnotationStandardInfoFields: true
Deserializing JannovarData from data/hg19_refseq.ser
Annotating VCF...
Deserialization took 15.12 sec.
Wrote annotations to "examples/small.jv.vcf"
Annotation and writing took 0.46 sec.
```

Unless it's in the current directory:
```
$ cp examples/small.vcf .
$ java -jar jannovar-cli-0.12.jar annotate data/hg19_refseq.ser small.vcf 
Options
verbosity: 1
dataFile: data/hg19_refseq.ser
vcfFilePaths: [small.vcf]
chromosomalChanges: []
showAll: false
jannovarFormat: false
writeJannovarInfoFields: false
writeVCFAnnotationStandardInfoFields: true
Deserializing JannovarData from data/hg19_refseq.ser
Annotating VCF...
Deserialization took 15.06 sec.
Exception in thread "main" java.lang.NullPointerException
	at java.io.File.<init>(File.java:251)
	at de.charite.compbio.jannovar.impl.util.PathUtil.join(PathUtil.java:27)
	at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotatedVCFWriter.getOutFileName(AnnotatedVCFWriter.java:62)
	at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotatedVCFWriter.<init>(AnnotatedVCFWriter.java:51)
	at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.run(AnnotateVCFCommand.java:54)
	at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:103)
```

Specifying the absolute path makes the error go away:
```
$ java -jar jannovar-cli-0.12.jar annotate data/hg19_refseq.ser `pwd`/small.vcf 
Options
verbosity: 1
dataFile: data/hg19_refseq.ser
vcfFilePaths: [/filer/tools/jannovar/jannovar-cli-0.12/small.vcf]
chromosomalChanges: []
showAll: false
jannovarFormat: false
writeJannovarInfoFields: false
writeVCFAnnotationStandardInfoFields: true
Deserializing JannovarData from data/hg19_refseq.ser
Annotating VCF...Deserialization took 15.09 sec.

Wrote annotations to "/filer/tools/jannovar/jannovar-cli-0.12/small.jv.vcf"
Annotation and writing took 0.32 sec.
```

**Comment by holtgrewe** [comment]
Will be fixed in 0.13 release.
