### ISSUE TITLE
GenomeChange throwing NullPointerException in toString() method.

### ISSUE THREAD

**Issue by julesjacobsen** [charite/jannovar#155]
I've migrated exomiser to use the latest jannovar off develop branch and I'm getting problems with the GenomeChange.toString() method. 

In both these cases I think the Variant has not been annotated.

```
2015-04-28 14:30:30,379 ERROR org.thymeleaf.TemplateEngine [main] - [THYMELEAF][main] Exception processing template "results": Exception evaluating OGNL expression: "variantEvaluation.chromosomalVariant" (results:159)
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.028 sec <<< FAILURE! - in de.charite.compbio.exomiser.core.writers.HtmlResultsWriterTest
testWriteTemplateWithUnAnnotatedVariantDataAndGenes(de.charite.compbio.exomiser.core.writers.HtmlResultsWriterTest)  Time elapsed: 0.158 sec  <<< ERROR!
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating OGNL expression: "variantEvaluation.chromosomalVariant" (results:159)
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
	at com.google.common.base.Joiner.toString(Joiner.java:433)
	at com.google.common.base.Joiner.appendTo(Joiner.java:108)
	at com.google.common.base.Joiner.appendTo(Joiner.java:152)
	at com.google.common.base.Joiner.join(Joiner.java:193)
	at com.google.common.base.Joiner.join(Joiner.java:183)
	at com.google.common.base.Joiner.join(Joiner.java:209)
	at de.charite.compbio.jannovar.reference.GenomeChange.toString(GenomeChange.java:212)
	at de.charite.compbio.exomiser.core.model.VariantEvaluation.getChromosomalVariant(VariantEvaluation.java:271)
```
```
Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.747 sec <<< FAILURE! - in de.charite.compbio.exomiser.core.factories.VariantFactoryTest
testCreateVariants_MultipleAllelesProduceOneVariantPerAllele(de.charite.compbio.exomiser.core.factories.VariantFactoryTest)  Time elapsed: 0.494 sec  <<< ERROR!
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
	at com.google.common.base.Joiner.toString(Joiner.java:433)
	at com.google.common.base.Joiner.appendTo(Joiner.java:108)
	at com.google.common.base.Joiner.appendTo(Joiner.java:152)
	at com.google.common.base.Joiner.join(Joiner.java:193)
	at com.google.common.base.Joiner.join(Joiner.java:183)
	at com.google.common.base.Joiner.join(Joiner.java:209)
	at de.charite.compbio.jannovar.reference.GenomeChange.toString(GenomeChange.java:212)
	at de.charite.compbio.exomiser.core.model.Variant.getChromosomalVariant(Variant.java:94)
	at de.charite.compbio.exomiser.core.factories.VariantFactoryTest.printVariant(VariantFactoryTest.java:46)
	at de.charite.compbio.exomiser.core.factories.VariantFactoryTest.testCreateVariants_MultipleAllelesProduceOneVariantPerAllele(VariantFactoryTest.java:86)
```

**Comment by julesjacobsen** [comment]
I'm not sure if it's due to a change you've made or some bug I've introduced with the new VariantFactory and VariantAnnotator classes, but I think it's likely one of your changes as it was all building fine before applying the new jannovar build.
