### ISSUE TITLE
What does java.lang.NullPointerException means using VCF file

### ISSUE THREAD

**Issue by frankMusacchia** [charite/jannovar#212]
Hi, 
I am using JAnnovar to annotate a VCF file after variant calling with GATK.
The same file I used in Annovar without problems makes Jannovar complain like this:

**### ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Options
verbosity: 1
dataFile: data/hg19_refseq.ser
vcfFilePaths: [../ticlip_works/Trio_VN_CGH06/phasing_out/Trio_VN_CGH06_genot_varfilt_phasing.vcf]
chromosomalChanges: []
showAll: true
jannovarFormat: false
writeJannovarInfoFields: false
writeVCFAnnotationStandardInfoFields: true
output infix: .jv
INFO Deserializing JannovarData from data/hg19_refseq.ser
INFO Deserialization took 6.64 sec.
Annotating VCF...
Exception in thread "main" java.lang.NullPointerException
	at de.charite.compbio.jannovar.annotation.Annotation.toVCFAnnoString(Annotation.java:268)
	at de.charite.compbio.jannovar.annotation.Annotation.toVCFAnnoString(Annotation.java:282)
	at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.applyStandardAnnotations(VariantContextAnnotator.java:250)
	at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.applyAnnotations(VariantContextAnnotator.java:238)
	at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotatedVCFWriter.put(AnnotatedVCFWriter.java:103)
	at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.run(AnnotateVCFCommand.java:59)
	at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:111)
**

What does this means?

Regards,

Francesco

**Comment by holtgrewe** [comment]
Hi Francesco, we are working on a solution to RefSeq making problems (actually we have a solution that is still pending validation).

In the meantime, please try to use Ensembl for annotating your variants.

I'll leave this issue open until we have the next release with a bug fix.

**Comment by frankMusacchia** [comment]
Ok. How can I use Ensembl or, even better, GenCode?

**Comment by holtgrewe** [comment]
Gencode is on our list but we don't have it yet.

Here is how to use Ensembl

```
# download ENSEMBL for hg19
java -jar jannovar-cli-0.16.jar download -d hg19/ensembl
# annotate using ENSEMBL
java -jar jannovar-cli-0.16.jar annotate -d data/hg19_ensembl.ser -i examples/small.vcf
```

**Comment by visze** [comment]
The problem should be fixed in the next release

**Comment by holtgrewe** [comment]
Version 0.17 is out, get it from Maven Central.

https://search.maven.org/#search%7Cga%7C1%7Cjannovar
