### ISSUE TITLE
UnsupportedClassVersionError

### ISSUE THREAD

**Issue by stolpeo** [charite/jannovar#257]
When I execute the Jannovar version downloaded from the [maven repository](https://mvnrepository.com/artifact/de.charite.compbio/jannovar-cli/0.17), I get the following error message:

```
$ java -jar jannovar-cli-0.17.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: de/charite/compbio/jannovar/Jannovar : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

```
$ java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
```

**Comment by visze** [comment]
Java 8 is required since jannovar 0.17 because we switched to htsjdk 2.x
and we want to use the new Java Stream io.

Oliver <notifications@github.com> schrieb am Di., 6. Sep. 2016 09:01:

**Comment by stolpeo** [comment]
Works like a charm, thanks.
