### ISSUE TITLE
Null pointer exception with refseq data

### ISSUE THREAD

**Issue by stolpeo** [charite/jannovar#258]
There seems to be an issue regarding refseq data and the jannovar refseq/GFF parser. I get a null pointer exception while processing different data sets:

```
$ java -jar jannovar-cli-0.17.jar download --data-dir test_jannovar -d hg19/refseq_curated 
Options
verbosity: 1
dataSourceFiles: [bundle:///default_sources.ini]
dataSourceNames: [hg19/refseq_curated]
downloadPathtest_jannovar
HTTP proxy: null
HTTPS proxy: null
FTP proxy: null
Downloading/parsing for data source "hg19/refseq_curated"
INFO Downloading data...
INFO Downloading ftp://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/ARCHIVE/ANNOTATION_RELEASE.105/GFF/ref_GRCh37.p13_top_level.gff3.gz
INFO Creating directory test_jannovar/hg19/refseq_curated
INFO (server did not tell us the file size, no progress bar)
INFO Downloading ftp://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/ARCHIVE/ANNOTATION_RELEASE.105/RNA/rna.fa.gz
INFO (server did not tell us the file size, no progress bar)
INFO Downloading http://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/chromInfo.txt.gz
[==================================================]   100%     
INFO Downloading ftp://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/ARCHIVE/ANNOTATION_RELEASE.105/Assembled_chromosomes/chr_accessions_GRCh37.p13
INFO (server did not tell us the file size, no progress bar)
INFO Building ReferenceDictionary...
INFO Parsing transcripts...
INFO Determined GTF/GFF file version to be GFF3
INFO Loaded 1936560 GFF records for 44939 genes
Exception in thread "main" java.lang.NullPointerException
	at de.charite.compbio.jannovar.impl.parse.refseq.RefSeqParser.processGeneGFFRecords(RefSeqParser.java:264)
	at de.charite.compbio.jannovar.impl.parse.refseq.RefSeqParser.recordsToBuilders(RefSeqParser.java:166)
	at de.charite.compbio.jannovar.impl.parse.refseq.RefSeqParser.run(RefSeqParser.java:79)
	at de.charite.compbio.jannovar.datasource.RefSeqJannovarDataFactory.parseTranscripts(RefSeqJannovarDataFactory.java:38)
	at de.charite.compbio.jannovar.datasource.JannovarDataFactory.build(JannovarDataFactory.java:99)
	at de.charite.compbio.jannovar.cmd.download.DownloadCommand.run(DownloadCommand.java:42)
	at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:111)
```

```
$ java -jar jannovar-cli-0.17.jar download --data-dir test_jannovar -d mm9/refseq
Options
verbosity: 1
dataSourceFiles: [bundle:///default_sources.ini]
dataSourceNames: [mm9/refseq]
downloadPathtest_jannovar
HTTP proxy: null
HTTPS proxy: null
FTP proxy: null
Downloading/parsing for data source "mm9/refseq"
INFO Downloading data...
INFO Downloading ftp://ftp.ncbi.nlm.nih.gov/genomes/M_musculus/ARCHIVE/BUILD.37.2/GFF/ref_MGSCv37_top_level.gff3.gz
INFO Creating directory test_jannovar/mm9/refseq
INFO (server did not tell us the file size, no progress bar)
INFO Downloading ftp://ftp.ncbi.nlm.nih.gov/genomes/M_musculus/ARCHIVE/BUILD.37.2/RNA/rna.fa.gz
INFO (server did not tell us the file size, no progress bar)
INFO Downloading http://hgdownload.soe.ucsc.edu/goldenPath/mm9/database/chromInfo.txt.gz
[==================================================]   100%     
INFO Downloading ftp://ftp.ncbi.nlm.nih.gov/genomes/M_musculus/ARCHIVE/BUILD.37.2/Assembled_chromosomes/chr_accessions_MGSCv37
INFO (server did not tell us the file size, no progress bar)
INFO Building ReferenceDictionary...
INFO Parsing transcripts...
INFO Determined GTF/GFF file version to be GFF3
Exception in thread "main" java.lang.NullPointerException
	at de.charite.compbio.jannovar.impl.parse.refseq.RefSeqParser.loadRecords(RefSeqParser.java:342)
	at de.charite.compbio.jannovar.impl.parse.refseq.RefSeqParser.run(RefSeqParser.java:79)
	at de.charite.compbio.jannovar.datasource.RefSeqJannovarDataFactory.parseTranscripts(RefSeqJannovarDataFactory.java:38)
	at de.charite.compbio.jannovar.datasource.JannovarDataFactory.build(JannovarDataFactory.java:99)
	at de.charite.compbio.jannovar.cmd.download.DownloadCommand.run(DownloadCommand.java:42)
	at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:111)
```

```
$ java -jar jannovar-cli-0.17.jar download --data-dir test_jannovar -d hg38/refseq_curated
Options
verbosity: 1
dataSourceFiles: [bundle:///default_sources.ini]
dataSourceNames: [hg38/refseq_curated]
downloadPathtest_jannovar
HTTP proxy: null
HTTPS proxy: null
FTP proxy: null
Downloading/parsing for data source "hg38/refseq_curated"
INFO Downloading data...
INFO Downloading ftp://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/GFF/ref_GRCh38.p7_top_level.gff3.gz
INFO Creating directory test_jannovar/hg38/refseq_curated
INFO (server did not tell us the file size, no progress bar)
INFO Downloading ftp://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/RNA/rna.fa.gz
INFO (server did not tell us the file size, no progress bar)
INFO Downloading http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/chromInfo.txt.gz
[==================================================]   100%     
INFO Downloading ftp://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/Assembled_chromosomes/chr_accessions_GRCh38.p7
INFO (server did not tell us the file size, no progress bar)
INFO Building ReferenceDictionary...
INFO Parsing transcripts...
INFO Determined GTF/GFF file version to be GFF3
INFO Loaded 3519976 GFF records for 59894 genes
Exception in thread "main" java.lang.NullPointerException
	at de.charite.compbio.jannovar.impl.parse.refseq.RefSeqParser.processGeneGFFRecords(RefSeqParser.java:264)
	at de.charite.compbio.jannovar.impl.parse.refseq.RefSeqParser.recordsToBuilders(RefSeqParser.java:166)
	at de.charite.compbio.jannovar.impl.parse.refseq.RefSeqParser.run(RefSeqParser.java:79)
	at de.charite.compbio.jannovar.datasource.RefSeqJannovarDataFactory.parseTranscripts(RefSeqJannovarDataFactory.java:38)
	at de.charite.compbio.jannovar.datasource.JannovarDataFactory.build(JannovarDataFactory.java:99)
	at de.charite.compbio.jannovar.cmd.download.DownloadCommand.run(DownloadCommand.java:42)
	at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:111)
```

**Comment by visze** [comment]
thx Oliver: I have took at this in detailed. refseq always makes trouble. And this time it is not the case that they changed their URLs. :-(

**Comment by visze** [comment]
Found the bug and added a fix. It only appears for the refseq curated versions!
@holtgrewe can you prepare a hotfix version 0.17.1?
