### ISSUE TITLE
bug in downloading refseq database using download-dir folder

### ISSUE THREAD

**Issue by visze** [charite/jannovar#269]
```
java -jar jannovar/jannovar-cli-0.18-SNAPSHOT.jar download -d hg19/refseq --download-dir jannovar 
```
```
...
INFO Building ReferenceDictionary...
Exception in thread "main" java.lang.IndexOutOfBoundsException: index (0) must be less than size (0)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:310)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:293)
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:67)
	at de.charite.compbio.jannovar.impl.parse.ReferenceDictParser.parse(ReferenceDictParser.java:127)
	at de.charite.compbio.jannovar.datasource.JannovarDataFactory.build(JannovarDataFactory.java:94)
	at de.charite.compbio.jannovar.cmd.download.DownloadCommand.run(DownloadCommand.java:41)
	at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:61)
```

without the `--download-dir` option it works fine!

**Comment by holtgrewe** [comment]
worksforme
