### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by bengyunfu** [charite/jannovar#287]
When I run jannovar-cli-0.18.jar annotate-vcf , I got some problems.

The exception is:
```
Extending header with INHERITANCE...
Exception in thread "main" java.lang.NullPointerException
at de.charite.compbio.jannovar.mendel.filter.GeneWiseMendelianAnnotationProcessor.put(GeneWiseMendelianAnnotationProcessor.java:115)
at de.charite.compbio.jannovar.mendel.filter.CoordinateSortingChecker.put(CoordinateSortingChecker.java:46)
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
at java.util.Iterator.forEachRemaining(Iterator.java:116)
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.run(AnnotateVCFCommand.java:133)
at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:62)
```

I try to debug it but I hardly read it because of the long relationship or chain. So I search for help here.

Commandline is:
`java -Xms4G -Xms4G -jar ~/tools/jannovar/jannovar-cli-0.18.jar annotate-vcf -d ~/tools/jannovar/data/hg19_refseq.ser -i partital.vcf -o ped_result_v2.vcf --pedigree-file ../../lung_cancer.ped`

After I search from google, I guess it is the problem from my vcf inputed.

So I want to know what the situation will cause this error. Thank you

**Comment by bengyunfu** [comment]
For more details, I would like to complement about the vcf I got. I was using bcftools merge to get multi-sample vcf. Does it gone cause problems?

**Comment by visze** [comment]
I think it is not a problem with the vcf. Maybe a rare vcf line causes this but this is the problem of our implementation. Can you check it if it runs trough without the pedigree-file?

**Comment by bengyunfu** [comment]
Yes, it can work. But it seem that it just write one vcf to another vcf without any change. So does it mean maybe it is the problem of my pedigree-file?

**Comment by bengyunfu** [comment]
So I would like to cat my head of the vcf file to there.
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##FILTER=<ID=LowQual,Description="Low quality">
##FILTER=<ID=my_indel_filter,Description="QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0">
##FILTER=<ID=my_snp_filter,Description="QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
##INFO=<ID=ABHet,Number=1,Type=Float,Description="Allele Balance for heterozygous calls (ref/(ref+alt))">
##INFO=<ID=ABHom,Number=1,Type=Float,Description="Allele Balance for homozygous calls (A/(A+O)) where A is the allele (ref or alt) and O is anything other">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=BaseQRankSum,Number=1,Type=Float,Description="Z-score from Wilcoxon rank sum test of Alt Vs. Ref base qualities">
##INFO=<ID=ClippingRankSum,Number=1,Type=Float,Description="Z-score From Wilcoxon rank sum test of Alt vs. Ref number of hard clipped bases">
##INFO=<ID=DB,Number=0,Type=Flag,Description="dbSNP Membership">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth; some reads may have been filtered">
##INFO=<ID=DS,Number=0,Type=Flag,Description="Were any of the samples downsampled?">
##INFO=<ID=ExcessHet,Number=1,Type=Float,Description="Phred-scaled p-value for exact test of excess heterozygosity">
##INFO=<ID=FS,Number=1,Type=Float,Description="Phred-scaled p-value using Fisher's exact test to detect strand bias">
##INFO=<ID=HaplotypeScore,Number=1,Type=Float,Description="Consistency of the site with at most two segregating haplotypes">
##INFO=<ID=InbreedingCoeff,Number=1,Type=Float,Description="Inbreeding coefficient as estimated from the genotype likelihoods per-sample when compared against the Hardy-Weinberg expectation">
##INFO=<ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed">
##INFO=<ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allele, in the same order as listed">
##INFO=<ID=MQ,Number=1,Type=Float,Description="RMS Mapping Quality">
##INFO=<ID=MQRankSum,Number=1,Type=Float,Description="Z-score From Wilcoxon rank sum test of Alt vs. Ref read mapping qualities">
##INFO=<ID=OND,Number=1,Type=Float,Description="Overall non-diploid ratio (alleles/(alleles+non-alleles))">
##INFO=<ID=QD,Number=1,Type=Float,Description="Variant Confidence/Quality by Depth">
##INFO=<ID=ReadPosRankSum,Number=1,Type=Float,Description="Z-score from Wilcoxon rank sum test of Alt vs. Ref read position bias">
##INFO=<ID=SOR,Number=1,Type=Float,Description="Symmetric Odds Ratio of 2x2 contingency table to detect strand bias">
##INFO=<ID=set,Number=1,Type=String,Description="Source VCF for the merged record in CombineVariants">
##contig=<ID=chrM,length=16571,assembly=hg19>
##contig=<ID=chr1,length=249250621,assembly=hg19>
##contig=<ID=chr2,length=243199373,assembly=hg19>
##contig=<ID=chr3,length=198022430,assembly=hg19>
##contig=<ID=chr4,length=191154276,assembly=hg19>
##contig=<ID=chr5,length=180915260,assembly=hg19>
##contig=<ID=chr6,length=171115067,assembly=hg19>
##contig=<ID=chr7,length=159138663,assembly=hg19>
##contig=<ID=chr8,length=146364022,assembly=hg19>
##contig=<ID=chr9,length=141213431,assembly=hg19>
##contig=<ID=chr10,length=135534747,assembly=hg19>
##contig=<ID=chr11,length=135006516,assembly=hg19>
##contig=<ID=chr12,length=133851895,assembly=hg19>
##contig=<ID=chr13,length=115169878,assembly=hg19>
##contig=<ID=chr14,length=107349540,assembly=hg19>
##contig=<ID=chr15,length=102531392,assembly=hg19>
##contig=<ID=chr16,length=90354753,assembly=hg19>
##contig=<ID=chr17,length=81195210,assembly=hg19>
##contig=<ID=chr18,length=78077248,assembly=hg19>
##contig=<ID=chr19,length=59128983,assembly=hg19>
##contig=<ID=chr20,length=63025520,assembly=hg19>
##contig=<ID=chr21,length=48129895,assembly=hg19>
##contig=<ID=chr22,length=51304566,assembly=hg19>
##contig=<ID=chrX,length=155270560,assembly=hg19>
##contig=<ID=chrY,length=59373566,assembly=hg19>
##contig=<ID=chr1_gl000191_random,length=106433,assembly=hg19>
##contig=<ID=chr1_gl000192_random,length=547496,assembly=hg19>
##contig=<ID=chr4_ctg9_hap1,length=590426,assembly=hg19>
##contig=<ID=chr4_gl000193_random,length=189789,assembly=hg19>
##contig=<ID=chr4_gl000194_random,length=191469,assembly=hg19>
##contig=<ID=chr6_apd_hap1,length=4622290,assembly=hg19>
##contig=<ID=chr6_cox_hap2,length=4795371,assembly=hg19>
##contig=<ID=chr6_dbb_hap3,length=4610396,assembly=hg19>
##contig=<ID=chr6_mann_hap4,length=4683263,assembly=hg19>
##contig=<ID=chr6_mcf_hap5,length=4833398,assembly=hg19>
##contig=<ID=chr6_qbl_hap6,length=4611984,assembly=hg19>
##contig=<ID=chr6_ssto_hap7,length=4928567,assembly=hg19>
##contig=<ID=chr7_gl000195_random,length=182896,assembly=hg19>
##contig=<ID=chr8_gl000196_random,length=38914,assembly=hg19>
##contig=<ID=chr8_gl000197_random,length=37175,assembly=hg19>
##contig=<ID=chr9_gl000198_random,length=90085,assembly=hg19>
##contig=<ID=chr9_gl000199_random,length=169874,assembly=hg19>
##contig=<ID=chr9_gl000200_random,length=187035,assembly=hg19>
##contig=<ID=chr9_gl000201_random,length=36148,assembly=hg19>
##contig=<ID=chr11_gl000202_random,length=40103,assembly=hg19>
##contig=<ID=chr17_ctg5_hap1,length=1680828,assembly=hg19>
##contig=<ID=chr17_gl000203_random,length=37498,assembly=hg19>
##contig=<ID=chr17_gl000204_random,length=81310,assembly=hg19>
##contig=<ID=chr17_gl000205_random,length=174588,assembly=hg19>
##contig=<ID=chr17_gl000206_random,length=41001,assembly=hg19>
##contig=<ID=chr18_gl000207_random,length=4262,assembly=hg19>
##contig=<ID=chr19_gl000208_random,length=92689,assembly=hg19>
##contig=<ID=chr19_gl000209_random,length=159169,assembly=hg19>
##contig=<ID=chr21_gl000210_random,length=27682,assembly=hg19>
##contig=<ID=chrUn_gl000211,length=166566,assembly=hg19>
##contig=<ID=chrUn_gl000212,length=186858,assembly=hg19>
##contig=<ID=chrUn_gl000213,length=164239,assembly=hg19>
##contig=<ID=chrUn_gl000214,length=137718,assembly=hg19>
##contig=<ID=chrUn_gl000215,length=172545,assembly=hg19>
##contig=<ID=chrUn_gl000216,length=172294,assembly=hg19>
##contig=<ID=chrUn_gl000217,length=172149,assembly=hg19>
##contig=<ID=chrUn_gl000218,length=161147,assembly=hg19>
##contig=<ID=chrUn_gl000219,length=179198,assembly=hg19>
##contig=<ID=chrUn_gl000220,length=161802,assembly=hg19>
##contig=<ID=chrUn_gl000221,length=155397,assembly=hg19>
##contig=<ID=chrUn_gl000222,length=186861,assembly=hg19>
##contig=<ID=chrUn_gl000223,length=180455,assembly=hg19>
##contig=<ID=chrUn_gl000224,length=179693,assembly=hg19>
##contig=<ID=chrUn_gl000225,length=211173,assembly=hg19>
##contig=<ID=chrUn_gl000226,length=15008,assembly=hg19>
##contig=<ID=chrUn_gl000227,length=128374,assembly=hg19>
##contig=<ID=chrUn_gl000228,length=129120,assembly=hg19>
##contig=<ID=chrUn_gl000229,length=19913,assembly=hg19>
##contig=<ID=chrUn_gl000230,length=43691,assembly=hg19>
##contig=<ID=chrUn_gl000231,length=27386,assembly=hg19>
##contig=<ID=chrUn_gl000232,length=40652,assembly=hg19>
##contig=<ID=chrUn_gl000233,length=45941,assembly=hg19>
##contig=<ID=chrUn_gl000234,length=40531,assembly=hg19>
##contig=<ID=chrUn_gl000235,length=34474,assembly=hg19>
##contig=<ID=chrUn_gl000236,length=41934,assembly=hg19>
##contig=<ID=chrUn_gl000237,length=45867,assembly=hg19>
##contig=<ID=chrUn_gl000238,length=39939,assembly=hg19>
##contig=<ID=chrUn_gl000239,length=33824,assembly=hg19>
##contig=<ID=chrUn_gl000240,length=41933,assembly=hg19>
##contig=<ID=chrUn_gl000241,length=42152,assembly=hg19>
##contig=<ID=chrUn_gl000242,length=43523,assembly=hg19>
##contig=<ID=chrUn_gl000243,length=43341,assembly=hg19>
##contig=<ID=chrUn_gl000244,length=39929,assembly=hg19>
##contig=<ID=chrUn_gl000245,length=36651,assembly=hg19>
##contig=<ID=chrUn_gl000246,length=38154,assembly=hg19>
##contig=<ID=chrUn_gl000247,length=36422,assembly=hg19>
##contig=<ID=chrUn_gl000248,length=39786,assembly=hg19>
##contig=<ID=chrUn_gl000249,length=38502,assembly=hg19>
##reference=file:///home/liaoth/project/db/hg19/ucsc.hg19.fasta
##source=SelectVariants
##bcftools_mergeVersion=1.2+htslib-1.2.1
##bcftools_mergeCommand=merge -i - -o merged_v2.vcf 1-1-1_S4.merged.vcf.gz 1-1-2_S5.merged.vcf.gz 1-1_S1.merged.vcf.gz 1-2_S3.merged.vcf.gz 1-3-1_S2.merged.vcf.gz 1-5-1_S7.merged.vcf.gz 1-5_S6.merged.vcf.gz
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	1-1-1_S4	1-1-2_S5	1-1_S1	1-2_S3	1-3-1_S2	1-5-1_S7	1-5_S6
```
And also the pedigree file.
```
FAM	1-1_S1	0-1	0-2	2	1
FAM	1-1-1_S4	0	1-1_S1	0	0
FAM	1-1-2_S5	0	1-1_S1	0	0
FAM	1-3-1_S2	1-3	0	0	0
FAM	1-5_S6	0-1	0-2	1	0
FAM	1-5-1_S7	1-5_S6	0	0	0
FAM	1-2_S3	0-1	0-2	2	1
FAM	1-0	0-1	0-2	1	1
FAM	1-4	0-1	0-2	2	2
FAM	0-1	0	0	1	2
FAM	0-2	0	0	2	2
FAM	1-3	0-1	0-2	1	1
```

**Comment by visze** [comment]
I get the same error with our vcfs. So it is a bug in jannovar!

**Comment by visze** [comment]
The transcript database of chrM is not parsed. Therefore the list of contigid 25 is empty.  (tested with refseq)

1. Load the chrM transcript (might be not possible because transcripts are not defined in the gff)
2. When building the genotype list be sure that for every chromosome an arralist is present (maybe without genes). I have an example implementation here: https://github.com/charite/jannovar/compare/develop...visze:hotfix/null_geneList_for_inheritance

**Comment by bengyunfu** [comment]
Thank for your effort!!!

**Comment by bengyunfu** [comment]
Hello again, I try to fix this problems by recompiling through your revised code. But I got another NullPointerException happen at 

`Exception in thread "main" java.lang.NullPointerException
	at de.charite.compbio.jannovar.mendel.impl.MendelianCheckerARCompoundHet.collectTrioCandidates(MendelianCheckerARCompoundHet.java:149)
	at de.charite.compbio.jannovar.mendel.impl.MendelianCheckerARCompoundHet.filterCompatibleRecordsMultiSample(MendelianCheckerARCompoundHet.java:74)
	at de.charite.compbio.jannovar.mendel.impl.MendelianCheckerARCompoundHet.filterCompatibleRecords(MendelianCheckerARCompoundHet.java:55)
	at de.charite.compbio.jannovar.mendel.impl.MendelianCheckerAR.filterCompatibleRecords(MendelianCheckerAR.java:41)
	at de.charite.compbio.jannovar.mendel.MendelianInheritanceChecker.filterCompatibleRecords(MendelianInheritanceChecker.java:93)
	at de.charite.compbio.jannovar.mendel.MendelianInheritanceChecker.checkMendelianInheritance(MendelianInheritanceChecker.java:67)
	at de.charite.compbio.jannovar.mendel.bridge.VariantContextMendelianAnnotator.computeCompatibleInheritanceModes(VariantContextMendelianAnnotator.java:138)
	at de.charite.compbio.jannovar.mendel.filter.GeneWiseMendelianAnnotationProcessor.checkVariantsForGene(GeneWiseMendelianAnnotationProcessor.java:264)
	at de.charite.compbio.jannovar.mendel.filter.GeneWiseMendelianAnnotationProcessor.processedGene(GeneWiseMendelianAnnotationProcessor.java:283)
	at de.charite.compbio.jannovar.mendel.filter.GeneWiseMendelianAnnotationProcessor.markDoneGenes(GeneWiseMendelianAnnotationProcessor.java:241)
	at de.charite.compbio.jannovar.mendel.filter.GeneWiseMendelianAnnotationProcessor.put(GeneWiseMendelianAnnotationProcessor.java:126)
	at de.charite.compbio.jannovar.mendel.filter.CoordinateSortingChecker.put(CoordinateSortingChecker.java:46)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
	at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.run(AnnotateVCFCommand.java:133)
	at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:62)
	Suppressed: java.lang.NullPointerException
		at de.charite.compbio.jannovar.mendel.impl.MendelianCheckerARCompoundHet.collectTrioCandidates(MendelianCheckerARCompoundHet.java:149)
		at de.charite.compbio.jannovar.mendel.impl.MendelianCheckerARCompoundHet.filterCompatibleRecordsMultiSample(MendelianCheckerARCompoundHet.java:74)
		at de.charite.compbio.jannovar.mendel.impl.MendelianCheckerARCompoundHet.filterCompatibleRecords(MendelianCheckerARCompoundHet.java:55)
		at de.charite.compbio.jannovar.mendel.impl.MendelianCheckerAR.filterCompatibleRecords(MendelianCheckerAR.java:41)
		at de.charite.compbio.jannovar.mendel.MendelianInheritanceChecker.filterCompatibleRecords(MendelianInheritanceChecker.java:93)
		at de.charite.compbio.jannovar.mendel.MendelianInheritanceChecker.checkMendelianInheritance(MendelianInheritanceChecker.java:67)
		at de.charite.compbio.jannovar.mendel.bridge.VariantContextMendelianAnnotator.computeCompatibleInheritanceModes(VariantContextMendelianAnnotator.java:138)
		at de.charite.compbio.jannovar.mendel.filter.GeneWiseMendelianAnnotationProcessor.checkVariantsForGene(GeneWiseMendelianAnnotationProcessor.java:264)
		at de.charite.compbio.jannovar.mendel.filter.GeneWiseMendelianAnnotationProcessor.processedGene(GeneWiseMendelianAnnotationProcessor.java:283)
		at de.charite.compbio.jannovar.mendel.filter.GeneWiseMendelianAnnotationProcessor.markDoneGenes(GeneWiseMendelianAnnotationProcessor.java:241)
		at de.charite.compbio.jannovar.mendel.filter.GeneWiseMendelianAnnotationProcessor.close(GeneWiseMendelianAnnotationProcessor.java:150)
		at de.charite.compbio.jannovar.mendel.filter.CoordinateSortingChecker.close(CoordinateSortingChecker.java:53)
		at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.run(AnnotateVCFCommand.java:139)
		... 1 more
`


I think it doesn't raised because of the code I recompiled. So doesn't it exist another problems like that at collectTrioCandidates???

**Comment by visze** [comment]
this issue is still open and not fixed yet

**Comment by visze** [comment]
fix #293 does nopt fix the job! using refseq we still have the problem. I am really sure it is because of `chrM`. Just have a look here: https://github.com/charite/jannovar/compare/develop...visze:hotfix/null_geneList_for_inheritance

```
java -jar jannovar-cli/target/jannovar-cli-0.20-SNAPSHOT.jar annotate-vcf -d hg19_refseq.ser -i test.vcf.gz -o /tmp/test.vcf.gz --pedigree-file test.ped
```

```
Exception in thread "main" java.lang.NullPointerException
	at de.charite.compbio.jannovar.progress.GenomeRegionListFactoryFromSAMSequenceDictionary.construct(GenomeRegionListFactoryFromSAMSequenceDictionary.java:17)
	at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.run(AnnotateVCFCommand.java:81)
	at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:62)

```

**Comment by visze** [comment]
Now there is a new bug:
```
Exception in thread "main" java.lang.NullPointerException
	at de.charite.compbio.jannovar.mendel.filter.GeneWiseMendelianAnnotationProcessor$1.compare(GeneWiseMendelianAnnotationProcessor.java:322)
	at de.charite.compbio.jannovar.mendel.filter.GeneWiseMendelianAnnotationProcessor$1.compare(GeneWiseMendelianAnnotationProcessor.java:319)
	at de.charite.compbio.jannovar.mendel.filter.GeneWiseMendelianAnnotationProcessor.lambda$processedGene$7(GeneWiseMendelianAnnotationProcessor.java:335)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at de.charite.compbio.jannovar.mendel.filter.GeneWiseMendelianAnnotationProcessor.processedGene(GeneWiseMendelianAnnotationProcessor.java:336)
	at de.charite.compbio.jannovar.mendel.filter.GeneWiseMendelianAnnotationProcessor.markDoneGenes(GeneWiseMendelianAnnotationProcessor.java:250)
	at de.charite.compbio.jannovar.mendel.filter.GeneWiseMendelianAnnotationProcessor.put(GeneWiseMendelianAnnotationProcessor.java:135)
	at de.charite.compbio.jannovar.mendel.filter.CoordinateSortingChecker.put(CoordinateSortingChecker.java:46)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:590)
	at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.run(AnnotateVCFCommand.java:141)
	at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:62)
```

**Comment by bengyunfu** [comment]
Thank you very much for your patient. I am looking forward for next version of your programme.

**Comment by visze** [comment]
now it works on develop!

**Comment by holtgrewe** [comment]
Please test. I'll try to release 0.20 to Maven Central on Monday afternoon (Berlin Time)
