### ISSUE TITLE
Unsupported dbSNP build

### ISSUE THREAD

**Issue by martenj** [charite/jannovar#302]
Jannovar master v0.19

jannovar-cli-0.19.jar annotate-vcf ...

``
ERROR: Unsupported dbSNP build ID 149 only supported is b174
de.charite.compbio.jannovar.vardbs.base.JannovarVarDBException: Unsupported dbSNP build ID 149 only supported is b174
        at de.charite.compbio.jannovar.vardbs.dbsnp.DBSNPAnnotationDriver.<init>(DBSNPAnnotationDriver.java:45)
        at de.charite.compbio.jannovar.vardbs.facade.DBVariantContextAnnotatorFactory.constructDBSNP(DBVariantContextAnnotatorFactory.java:32)
        at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.run(AnnotateVCFCommand.java:95)
        at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:62)
``

**Comment by visze** [comment]
v0.19 is buggy. What about v0.20? Same error?

**Comment by martenj** [comment]
since I'm not able to compile the v0.20 I can not test it.

**Comment by holtgrewe** [comment]
What about the release v0.20 version?

**Comment by holtgrewe** [comment]
Reopen if the problem persists.

**Comment by zslastman** [comment]
@all it looks like b174 is a bug, it should be b147 in the error message.

**Comment by visze** [comment]
thx. I fixed it.
