### ISSUE TITLE
shiftedFrameDeletion causing StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by buske** [charite/jannovar#31]
Getting an error processing the following variant: ```chr1:g.167385324,TA->-```

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 10
	at java.lang.String.charAt(String.java:658)
	at jannovar.annotation.DeletionAnnotation.shiftedFrameDeletion(DeletionAnnotation.java:379)
	at jannovar.annotation.DeletionAnnotation.getMultinucleotideDeletionAnnotation(DeletionAnnotation.java:306)
	at jannovar.reference.Chromosome.annotateExonicVariants(Chromosome.java:884)
	at jannovar.reference.Chromosome.getPlusStrandAnnotation(Chromosome.java:551)
	at jannovar.reference.Chromosome.getAnnotationList(Chromosome.java:188)
[...]
```

**Comment by holtgrewe** [comment]
Please try again with version 0.12 if the problem persists and open again.
