### ISSUE TITLE
nicer exeption message when --ref-fasta command is missing

### ISSUE THREAD

**Issue by visze** [charite/jannovar#340]
When annotating with genomad but missing the reference fasta we get a very ugly exception with no hint that the reference fasta is missing:

command:
```
java de.charite.compbio.jannovar.Jannovar annotate-vcf --gnomad-exomes-vcf gnomad.exomes.r2.0.1.sites.vcf.gz -d data/hg19_refseq.ser -i fam1_AD.vcf -o fam1_AD.jv21.vcf 
```

error:
```
Annotating VCF...
Will read full input file
Exception in thread "main" java.lang.NullPointerException
    at java.io.File.<init>(File.java:277)
    at de.charite.compbio.jannovar.vardbs.base.VariantNormalizer.<init>(VariantNormalizer.java:37)
    at de.charite.compbio.jannovar.vardbs.base.AlleleMatcher.<init>(AlleleMatcher.java:30)
    at de.charite.compbio.jannovar.vardbs.base.AbstractDBAnnotationDriver.<init>(AbstractDBAnnotationDriver.java:47)
    at de.charite.compbio.jannovar.vardbs.gnomad.GnomadAnnotationDriver.<init>(GnomadAnnotationDriver.java:29)
    at de.charite.compbio.jannovar.vardbs.facade.DBVariantContextAnnotatorFactory.constructGnomad(DBVariantContextAnnotatorFactory.java:70)
    at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.run(AnnotateVCFCommand.java:163)
    at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:64)
```

**Comment by holtgrewe** [comment]
927ca7780ee273258d3126dd54828ed383d65dd4
