### ISSUE TITLE
Jannovar returns code 0 when .ped file is missing

### ISSUE THREAD

**Issue by stolpeo** [charite/jannovar#341]
When using Jannovar for inheritance annotation and the pedigree file is actually missing,
Jannovar returns 0 instead of an error code:

	$ java -jar jannovar-cli-0.22-SNAPSHOT.jar annotate-vcf \
		--ref-fasta hs37.fa \
		-i sample.vcf.gz \
		-o sample.jv.vcf.gz \
		-d hg19_refseq.ser \
		--inheritance-anno-use-filters \
		--pedigree-file sample.ped  # THIS FILE IS MISSING

	[...]
	VCF file sample.vcf.gz is not compatible to pedigree file sample.ped
	The VCF file has the following sample names not present in Pedigree: sample

	de.charite.compbio.jannovar.mendel.IncompatiblePedigreeException: The VCF file has the following sample names not present in Pedigree: sample
		at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.checkPedigreeCompatibility(AnnotateVCFCommand.java:390)
		at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.buildMendelianProcessors(AnnotateVCFCommand.java:364)
		at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.run(AnnotateVCFCommand.java:281)
		at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:64)
	hs37d5:1	0	Infinity	100.0%	6.4 min	0 s

	$ echo $?
	0

**Comment by stolpeo** [comment]
User error, so I close the ticket.
