### ISSUE TITLE
Error on annotate-vcf (most likely due to no variants fitting model)

### ISSUE THREAD

**Issue by MrsLaviniaG** [charite/jannovar#345]
Hi, I have an error with annotate-vcf which I suspect is because no variants fit the model, however the error does not specifically declare that:

java -jar jannovar-cli-0.21.jar annotate-vcf -d data/hg19_refseq.ser -i Case_AD.vcf -o casead.vcf --pedigree-file casead.ped
Options
JannovarAnnotateVCFOptions [escapeAnnField=true, pathInputVCF=Case_AD.vcf, interval=, pathOutputVCF=casead.vcf, pathVCFDBSNP=null, prefixDBSNP=DBSNP_, pathFASTARef=null, pathVCFExac=null, prefixExac=EXAC_, pathVCFGnomadExomes=null, prefixVCFGnomadExomes=GNOMAD_EXOMES_, pathVCFGnomadGenomes=null, prefixVCFGnomadGenomes=GNOMAD_GENOMES_, pathVCFUK10K=null, prefixUK10K=UK10K_, pathClinVar=null, prefixClinVar=CLINVAR_, pathCosmic=null, prefixCosmic=COSMIC_, pathPedFile=casead.ped, annotateAsSingletonPedigree=false, useThresholdFilters=false, threshFiltMinGtCovHet=8, threshFiltMinGtCovHomAlt=4, threshFiltMaxCov=10000, threshFiltMinGtGq=20, threshFiltMinGtAafHet=0.2, threshFiltMaxGtAafHet=0.8, threshFiltMinGtAafHomAlt=0.7, threshFiltMaxGtAafHomRef=0.3, threshFiltMaxAlleleFrequencyAd=0.01, threshFiltMaxAlleleFrequencyAr=0.01, offTargetFilterEnabled=false, offTargetFilterUtrIsOffTarget=false, offTargetFilterIntronicSpliceIsOffTarget=false, inheritanceAnnoUseFilters=false]
Deserializing transcripts...
INFO Deserializing JannovarData from data/hg19_refseq.ser
INFO Deserialization took 7.26 sec.
Location        processed.sites runtime.per.1M.sites    completed       total.runtime   remaining
Annotating VCF...
Will read full input file
Extending header with INHERITANCE...
Exception in thread "main" java.lang.NullPointerException
        at de.charite.compbio.jannovar.mendel.MendelianInheritanceChecker.filterCompatibleRecordsSub(MendelianInheritanceChecker.java:163)
        at de.charite.compbio.jannovar.mendel.bridge.VariantContextMendelianAnnotator.annotateRecords(VariantContextMendelianAnnotator.java:130)
        at de.charite.compbio.jannovar.mendel.bridge.VariantContextMendelianAnnotator.annotateRecord(VariantContextMendelianAnnotator.java:81)
        at de.charite.compbio.jannovar.mendel.filter.GeneWiseMendelianAnnotationProcessor.putVariantForGene(GeneWiseMendelianAnnotationProcessor.java:237)
        at de.charite.compbio.jannovar.mendel.filter.GeneWiseMendelianAnnotationProcessor.put(GeneWiseMendelianAnnotationProcessor.java:146)
        at de.charite.compbio.jannovar.mendel.filter.CoordinateSortingChecker.put(CoordinateSortingChecker.java:46)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
        at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.run(AnnotateVCFCommand.java:286)
        at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:64)

Jannovar downloaded 4/5/2017.

with regards,

Lavinia Gordon.

**Comment by visze** [comment]
Hi Lavinia,

thank you for reporting this issue. Jannovar should only annotate the inheritance and not filter them directly. If all variants do not fit to any inheritance it should still run trough and give you an output. So I think is a real bug.

Is it possible to give us the vcf and ped file? Maybe in shorten and anonymous form to reproduce the error?

**Comment by holtgrewe** [comment]
Could you try with the attached file?

[jannovar-cli-0.22-SNAPSHOT.jar.zip](https://github.com/charite/jannovar/files/976361/jannovar-cli-0.22-SNAPSHOT.jar.zip)

**Comment by holtgrewe** [comment]
Please try with released 0.22 version, otherwise reopen.
