### ISSUE TITLE
Can't annotate CADD scores from dbNSFP

### ISSUE THREAD

**Issue by la60312** [charite/jannovar#409]
Dear Jannovar,

I would like to annotate VCF file with dbNSFP3.5. However, there was an error while annotating CADD score. The version I used is Jannovar 0.25.

I used this command to annotate CADD_phred.
```
java -jar ../../jannovar-cli-0.25.jar annotate-vcf -d ../../data/hg19_refseq.ser --dbnsfp-tsv  /data/project/dbNSFP/dbNSFP.gz --dbnsfp-col-contig 8 --dbnsfp-col-position 9 --dbnsfp-prefix CADD_SNV_ --dbnsfp-columns CADD_phred --ref-fasta ../../referenceGenome/data/human_g1k_v37.fasta -i 28827.vcf.gz -o test.vcf.gz
```

I got this error.
```
Exception in thread "main" java.lang.RuntimeException: Unknown field from dbNSFP or not yet supported: CADD_phred
        at de.charite.compbio.jannovar.cmd.annotate_vcf.JannovarAnnotateVCFOptions.setFromArgs(JannovarAnnotateVCFOptions.java:411)
        at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.<init>(AnnotateVCFCommand.java:87)
        at de.charite.compbio.jannovar.cmd.annotate_vcf.JannovarAnnotateVCFOptions.lambda$setupParser$0(JannovarAnnotateVCFOptions.java:200)
        at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:58)
```

I checked this page and I found the string "CADD_phred" is in the list, but it seems like you didn't run builder.put() with CADD scores. I also checked SIFT_score and it works.
https://github.com/charite/jannovar/blob/master/jannovar-cli/src/main/java/de/charite/compbio/jannovar/cmd/annotate_vcf/DbNsfpFields.java

Did I used the command incorrectly?

Thank you.

**Comment by holtgrewe** [comment]
Hi, no, this is currently a limitation in dbNSFP support.
