### ISSUE TITLE
HGVS to VCF error. ANTLR version mismatch?

### ISSUE THREAD

**Issue by pnrobinson** [charite/jannovar#411]
I would like to reverse-annotate some HGVS encoded mm10 variants. I created a FAI and a dict file for mm10.fa and entered the following command
```
$ java -Xms2g -jar jannovar-cli-0.24.jar hgvs-to-vcf -d data/mm10_refseq.ser -i hgvs.txt -o example.vcf -r /<path>/mm10.fa 
```
My HGVS file was like this
```
NM_026273:c.T729A
```

I got the following error:
```
$ java -Xms2g -jar jannovar-cli-0.24.jar hgvs-to-vcf -d data/mm10_refseq.ser -i hgvs.txt -o example.vcf -r /<path>/mm10.fa 
Options
ProjectTranscriptToChromosomeOptions [pathInputText=hgvs.txt, pathOutputVCF=example.vcf, pathReferenceFASTA=/home/peter/data/ucsc/mm10/mm10.fa, toString()=JannovarAnnotationOptions [useThreeLetterAminoAcidCode=false, nt3PrimeShifting=false, showAll=false, databaseFilePath=data/mm10_refseq.ser, toString()=JannovarBaseOptions [reportProgress=true, httpProxy=null, httpsProxy=null, ftpProxy=null, verbosity=1]]]
Loading database file...
INFO Deserializing JannovarData from data/mm10_refseq.ser
INFO Deserialization took 7.04 sec.
Loading FASTA index...
Opening output VCF file...
ANTLR Tool version 4.6 used for code generation does not match the current runtime version 4.7ANTLR Tool version 4.6 used for code generation does not match the current runtime version 4.7line 1:0 mismatched input '<EOF>' expecting REFERENCE
Exception in thread "main" java.lang.IllegalStateException: failed to parse at line 1 due to mismatched input '<EOF>' expecting REFERENCE
	at de.charite.compbio.jannovar.hgvs.parser.HGVSParser$1.syntaxError(HGVSParser.java:80)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:299)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:124)
	at de.charite.compbio.jannovar.hgvs.parser.Antlr4HGVSParser.hgvs_variant(Antlr4HGVSParser.java:204)
	at de.charite.compbio.jannovar.hgvs.parser.HGVSParser.parseHGVSString(HGVSParser.java:51)
	at de.charite.compbio.jannovar.cmd.hgvs_to_vcf.ProjectTranscriptToChromosome.processFile(ProjectTranscriptToChromosome.java:154)
	at de.charite.compbio.jannovar.cmd.hgvs_to_vcf.ProjectTranscriptToChromosome.run(ProjectTranscriptToChromosome.java:75)
	at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:64)
Caused by: org.antlr.v4.runtime.InputMismatchException
	at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:242)
	at de.charite.compbio.jannovar.hgvs.parser.Antlr4HGVSParser.hgvs_variant(Antlr4HGVSParser.java:170)
	... 4 more
```

Jannovar does not compile with antlr v 4.6 (I tried to change this in the pom file). I am unsure where this error is coming from?

**Comment by holtgrewe** [comment]
It looks like your hgvs is not valid. You use amino acid syntax for coding sequence variants. Does c.729A>T work?

**Comment by pnrobinson** [comment]
whoops, of course --however, that does not seem to be the cause of the error

```
 $ cat hgvs.txt 
NM_026273:c.729T>A
[~/GIT/jannovar] $ zgrep NM_026273 data/mm10/refseq/rna.fa.gz 
>gi|141801722|ref|NM_026273.2| Mus musculus RIKEN cDNA 4930453N24 gene (4930453N24Rik), mRNA
[~/GIT/jannovar] $ java -Xms2g -jar jannovar-cli-0.24.jar hgvs-to-vcf -d data/mm10_refseq.ser -i hgvs.txt -o example.vcf -r /home/peter/data/ucsc/mm10/mm10.fa 
Options
ProjectTranscriptToChromosomeOptions [pathInputText=hgvs.txt, pathOutputVCF=example.vcf, pathReferenceFASTA=/home/peter/data/ucsc/mm10/mm10.fa, toString()=JannovarAnnotationOptions [useThreeLetterAminoAcidCode=false, nt3PrimeShifting=false, showAll=false, databaseFilePath=data/mm10_refseq.ser, toString()=JannovarBaseOptions [reportProgress=true, httpProxy=null, httpsProxy=null, ftpProxy=null, verbosity=1]]]
Loading database file...
INFO Deserializing JannovarData from data/mm10_refseq.ser
INFO Deserialization took 7.16 sec.
Loading FASTA index...
Opening output VCF file...
ANTLR Tool version 4.6 used for code generation does not match the current runtime version 4.7ANTLR Tool version 4.6 used for code generation does not match the current runtime version 4.7Could not translate variant NucleotideVariant [seqType=CODING_DNA, refID=NM_026273, proteinID=null, transcriptVersion=-1]: de.charite.compbio.jannovar.hgvs.bridge.CannotTranslateHGVSVariant: No transcript found for id NM_026273
[~/GIT/jannovar] $ cat example.vcf 
##fileformat=VCFv4.2
##ALT=<ID=ERROR,Description="Error in conversion">
##FILTER=<ID=PARSE_ERROR,Description="Problem in parsing original HGVS variant string, written out as variant at 1:g.1N>N">
##INFO=<ID=ERROR_MESSAGE,Number=1,Type=String,Description="Error message">
##INFO=<ID=ORIG_VAR,Number=1,Type=String,Description="Original HGVS variant string from input file to hgvs-to-vcf">
##contig=<ID=chr1,length=195471971>
##contig=<ID=chr10,length=130694993>
##contig=<ID=chr11,length=122082543>
##contig=<ID=chr12,length=120129022>
##contig=<ID=chr13,length=120421639>
##contig=<ID=chr14,length=124902244>
##contig=<ID=chr15,length=104043685>
##contig=<ID=chr16,length=98207768>
##contig=<ID=chr17,length=94987271>
##contig=<ID=chr18,length=90702639>
##contig=<ID=chr19,length=61431566>
##contig=<ID=chr2,length=182113224>
##contig=<ID=chr3,length=160039680>
##contig=<ID=chr4,length=156508116>
##contig=<ID=chr5,length=151834684>
##contig=<ID=chr6,length=149736546>
##contig=<ID=chr7,length=145441459>
##contig=<ID=chr8,length=129401213>
##contig=<ID=chr9,length=124595110>
##contig=<ID=chrX,length=171031299>
##contig=<ID=chrY,length=91744698>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
1	1	.	N	<ERROR>	.	PARSE_ERROR	ERROR_MESSAGE=Could+not+translate+HGVS+to+genomic+variant;ORIG_VAR=NM_026273%3Ac.729T%3EA
[~/GIT/jannovar] $ 
```
```

**Comment by holtgrewe** [comment]
I think the Antlr complaint is just noise.

Here is the signal:

```
Could not translate variant NucleotideVariant [seqType=CODING_DNA, refID=NM_026273, proteinID=null, transcriptVersion=-1]: de.charite.compbio.jannovar.hgvs.bridge.CannotTranslateHGVSVariant: No transcript found for id NM_026273
```

I think the HGVS specification asks for versioned transcripts, so you have to specify the transcript version, e.g., `NM_026273.2`.

- http://varnomen.hgvs.org/bg-material/refseq/

HTH

**Comment by pnrobinson** [comment]
Thanks, I can confirm your diagnosis -- the problem was the fact that the version number was missing from the HGVS string.

**Comment by mansi800** [comment]
@holtgrewe I am having the same issue as @pnrobinson had even tough my HGVS are in this format:  NM_000314.8(PTEN):c.823dup
NM_000314.8(PTEN):c.209+97T>C
NM_001126049.2(KLLN):c.-881G>A
NC_000010.10:g.89623305G>T

Still I am getting the following bug:
Could not translate variant NucleotideVariant [seqType=CODING_DNA, refID=NM_000314, proteinID=null, transcriptVersion=8]: de.charite.compbio.jannovar.hgvs.bridge.CannotTranslateHGVSVariant: No transcript found for id NM_000314.8
Could not translate variant NucleotideVariant [seqType=CODING_DNA, refID=NM_000314, proteinID=null, transcriptVersion=8]: de.charite.compbio.jannovar.hgvs.bridge.CannotTranslateHGVSVariant: No transcript found for id NM_000314.8
Could not translate variant NucleotideVariant [seqType=CODING_DNA, refID=NM_001126049, proteinID=null, transcriptVersion=2]: de.charite.compbio.jannovar.hgvs.bridge.CannotTranslateHGVSVariant: No transcript found for id NM_001126049.2
Could not translate variant NucleotideVariant [seqType=GENOMIC, refID=NC_000010, proteinID=null, transcriptVersion=10]: de.charite.compbio.jannovar.hgvs.bridge.CannotTranslateHGVSVariant: Currently only coding DNA ("c.") and non-coding DNA ("n.") coordinates are supported.

The command that I have used is :
java -jar jannovar-cli-0.36.jar hgvs-to-vcf -d refseq_105_hg19.ser -i pten_hgvs.txt -o pten_hgvs.vcf -r hg19.fasta

**Comment by holtgrewe** [comment]
@mansi800  sorry for the delay. Please see #529 for an answer. Shortly, version `.8` is not in the refseq that we use but only `.10`. Multi-version transcript databases are not something that we plan to support Jannovar for now. VariantValidator and other tools it uses do an excellent job, though.

**Comment by mansi800** [comment]
@holtgrewe  Thanks for helping me out. 
I tried VariantValidator but it is for vcf to hgvs conversion. Can you please suggest some good tools(having api version) that can be used to convert hgvs to vcf efficiently.

**Comment by holtgrewe** [comment]
@mansi800

Well, the manual indicates that you can also use HGVS notation

- https://variantvalidator.org/help/instructions/

Would the LOVD endpoint here help you?

- https://rest.variantvalidator.org/

Maybe this python could also come in handy.

- https://github.com/openvar/vv_hgvs/
