### ISSUE TITLE
Issue building .ser database

### ISSUE THREAD

**Issue by mmcneill123** [charite/jannovar#461]
Good evening, 

I'm hoping you can help me with an issue I'm having using Jannovar.0.31 with the Rat genome. Prior versions of Jannovar were able to build the rat genome. 

I"m using the ini file below:

[rn6/refseq]
type=refseq
alias=MT,M,chrM
onlyCurated=True
chromInfo=http://hgdownload.soe.ucsc.edu/goldenPath/rn6/database/chromInfo.txt.gz
chrToAccessions=https://ftp.ncbi.nlm.nih.gov/genomes/R_norvegicus/ARCHIVE/ANNOTATION_RELEASE.105/Assembled_chromosomes/chr_accessions_Rnor_6.0
chrToAccessions.format=chr_accessions
gff=https://ftp.ncbi.nlm.nih.gov/genomes/R_norvegicus/ARCHIVE/ANNOTATION_RELEASE.105/GFF/ref_Rnor_6.0_top_level.gff3.gz
rna=https://ftp.ncbi.nlm.nih.gov/genomes/R_norvegicus/ARCHIVE/ANNOTATION_RELEASE.105/RNA/rna.fa.gz

I'm running Jannovar like this:

$ java -jar jannovar-cli-0.31.jar download -s my_refseq.ini -d rn6/refseq

With this output:

Options
JannovarDownloadOptions [downloadDir=data, getDataSourceFiles()=[bundle:///default_sources.ini, /srv/shiny-server/HDR_design_tool/HDR_tool/lib/external/my_refseq.ini], isReportProgress()=true, getHttpProxy()=null, getHttpsProxy()=null, getFtpProxy()=null, geneIdentifiers=[], outputFile=]
Downloading/parsing for data source "rn6/refseq"
INFO Downloading data...
INFO Downloading https://ftp.ncbi.nlm.nih.gov/genomes/R_norvegicus/ARCHIVE/ANNOTATION_RELEASE.105/GFF/ref_Rnor_6.0_top_level.gff3.gz
INFO Downloaded file ref_Rnor_6.0_top_level.gff3.gz looks like a valid gzip'ed file
INFO Downloading https://ftp.ncbi.nlm.nih.gov/genomes/R_norvegicus/ARCHIVE/ANNOTATION_RELEASE.105/RNA/rna.fa.gz
INFO Downloaded file rna.fa.gz looks like a valid gzip'ed file
INFO Downloading http://hgdownload.soe.ucsc.edu/goldenPath/rn6/database/chromInfo.txt.gz
INFO Downloaded file chromInfo.txt.gz looks like a valid gzip'ed file
INFO Downloading https://ftp.ncbi.nlm.nih.gov/genomes/R_norvegicus/ARCHIVE/ANNOTATION_RELEASE.105/Assembled_chromosomes/chr_accessions_Rnor_6.0
INFO Downloading http://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/hgnc_complete_set.txt
INFO Building ReferenceDictionary...
INFO Parsing transcripts...
INFO Loading feature records
INFO Determined GTF/GFF file version to be GFF3
Exception in thread "main" java.lang.IllegalStateException: No CDS region found for coding transcript 'NM_080399.1'.
        at de.charite.compbio.jannovar.impl.parse.refseq.RefSeqParser.failIfCdsRegionExpected(RefSeqParser.java:458)
        at de.charite.compbio.jannovar.impl.parse.refseq.RefSeqParser.lambda$mapParentIdsToTranscriptModelsWithTxRegion$1(RefSeqParser.java:443)
        at java.util.HashMap.forEach(HashMap.java:1280)
        at de.charite.compbio.jannovar.impl.parse.refseq.RefSeqParser.mapParentIdsToTranscriptModelsWithTxRegion(RefSeqParser.java:435)
        at de.charite.compbio.jannovar.impl.parse.refseq.RefSeqParser.mapTranscriptIdsToTranscriptModels(RefSeqParser.java:428)
        at de.charite.compbio.jannovar.impl.parse.refseq.RefSeqParser.loadTranscriptModels(RefSeqParser.java:312)
        at de.charite.compbio.jannovar.impl.parse.refseq.RefSeqParser.run(RefSeqParser.java:98)
        at de.charite.compbio.jannovar.datasource.RefSeqJannovarDataFactory.parseTranscripts(RefSeqJannovarDataFactory.java:36)
        at de.charite.compbio.jannovar.datasource.JannovarDataFactory.build(JannovarDataFactory.java:105)
        at de.charite.compbio.jannovar.cmd.download.DownloadCommand.run(DownloadCommand.java:43)
        at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:64)

**Comment by holtgrewe** [comment]
Hi @mmcneill123 :wave: Thanks for reporting this. I can build the rn6 `.ser` file without any problems (see below) with the v0.33 snapshot, should also work in the v0.32 release. Also note that rn6 with your INI configuration is included in Jannovar since v0.29. HTH

<details><summary>Click to see log with 0.33-SNAPSHOT</summary>
```
java -jar /vol/local/projects/jannovar/jannovar-cli/target/jannovar-cli-0.33-SNAPSHOT.jar download -d rn6/refseqOptions
JannovarDownloadOptions [downloadDir=data, getDataSourceFiles()=[bundle:///default_sources.ini], isReportProgress()=true, getHttpProxy()=null, getHttpsProxy()=null, getFtpProxy()=null, geneIdentifiers=[], outputFile=]
Downloading/parsing for data source "rn6/refseq"
INFO Downloading data...
INFO Downloading https://ftp.ncbi.nlm.nih.gov/genomes/R_norvegicus/ARCHIVE/ANNOTATION_RELEASE.105/GFF/ref_Rnor_6.0_top_level.gff3.gz
INFO Downloaded file ref_Rnor_6.0_top_level.gff3.gz looks like a valid gzip'ed file
INFO Downloading https://ftp.ncbi.nlm.nih.gov/genomes/R_norvegicus/ARCHIVE/ANNOTATION_RELEASE.105/RNA/rna.fa.gz
INFO Downloaded file rna.fa.gz looks like a valid gzip'ed file
INFO Downloading http://hgdownload.soe.ucsc.edu/goldenPath/rn6/database/chromInfo.txt.gz
INFO Downloaded file chromInfo.txt.gz looks like a valid gzip'ed file
INFO Downloading https://ftp.ncbi.nlm.nih.gov/genomes/R_norvegicus/ARCHIVE/ANNOTATION_RELEASE.105/Assembled_chromosomes/chr_accessions_Rnor_6.0
INFO Downloading http://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/hgnc_complete_set.txt
INFO Building ReferenceDictionary...
INFO Parsing transcripts...
INFO Loading feature records
INFO Determined GTF/GFF file version to be GFF3
WARN No CDS region found for coding transcript 'NM_080399.1'.
WARN No CDS region found for coding transcript 'NM_001107753.1'.
WARN No CDS region found for coding transcript 'NM_022666.1'.
WARN No CDS region found for coding transcript 'NM_024358.1'.
WARN No CDS region found for coding transcript 'NM_013150.1'.
WARN No CDS region found for coding transcript 'NM_012963.2'.
WARN No CDS region found for coding transcript 'NM_001190475.1'.
WARN Transcript NM_001190372.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001099495.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001047866.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001047865.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001108067.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001007701.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001190475.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_013150.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001108459.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_022292.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_024358.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001170534.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001271292.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001014114.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_020098.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001099463.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_012842.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_021767.2 has 3 possible transcript models - using the longest model
WARN Transcript NM_001195559.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001014271.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001271376.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_053594.2 has 2 possible transcript models - using the longest model
WARN Transcript NM_138823.2 has 2 possible transcript models - using the longest model
WARN Transcript NM_001134536.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001110797.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001271332.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001270415.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001134624.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001109338.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001134961.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001168559.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001271438.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_173302.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001271361.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001170593.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001085381.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_022666.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001107753.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001013918.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001012347.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001271404.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001191562.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_001011948.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_031504.3 has 2 possible transcript models - using the longest model
WARN Transcript NM_138903.1 has 2 possible transcript models - using the longest model
WARN Transcript NM_019235.2 has 2 possible transcript models - using the longest model
WARN Transcript NM_001134592.1 has 2 possible transcript models - using the longest model
WARN 47 duplicated transcript ids
INFO Parsed 1319386 GFF records as 60663 TranscriptModels
INFO Assigning additional HGNC information to 60663 transcripts..
INFO Ignoring 0 transcripts without sequence.
INFO Successfully processed 60663 transcripts with sequence.
WARN Number of alignment parts (9) != number of exons (8) for NM_001190372.1
WARN Number of alignment parts (11) != number of exons (4) for NM_001099495.1
WARN Number of alignment parts (34) != number of exons (23) for NM_001047866.1
WARN Number of alignment parts (8) != number of exons (10) for NM_001047865.1
WARN Number of alignment parts (1) != number of exons (22) for NM_001108067.1
WARN Number of alignment parts (26) != number of exons (24) for NM_001190475.1
WARN Number of alignment parts (30) != number of exons (3) for NM_013150.1
WARN Number of alignment parts (1) != number of exons (2) for NM_001108459.1
WARN Number of alignment parts (4) != number of exons (2) for NM_001103362.1
WARN Number of alignment parts (2) != number of exons (1) for NM_022292.1
WARN Number of alignment parts (36) != number of exons (34) for NM_024358.1
WARN Number of alignment parts (107) != number of exons (100) for NM_001271292.1
WARN Exon AlignmentPart{refBeginPos=3563066, refEndPos=3563190, txBeginPos=471, txEndPos=595, gap='M124'} does not match alignment part 10:g.3411380_3411661 (i=0, tx=NM_001014114.1)
WARN Number of alignment parts (35) != number of exons (23) for NM_020098.1
WARN Number of alignment parts (1) != number of exons (5) for NM_001099463.1
WARN Number of alignment parts (23) != number of exons (19) for NM_012842.1
WARN Number of alignment parts (27) != number of exons (16) for NM_021767.2
WARN Number of alignment parts (49) != number of exons (38) for NM_001271376.1
WARN Number of alignment parts (20) != number of exons (14) for NM_053594.2
WARN Number of alignment parts (8) != number of exons (5) for NM_138823.2
WARN Number of alignment parts (11) != number of exons (6) for NM_001134536.1
WARN Number of alignment parts (21) != number of exons (18) for NM_001110797.1
WARN Number of alignment parts (31) != number of exons (24) for NM_001271332.1
WARN Number of alignment parts (25) != number of exons (21) for NM_001270415.1
WARN Number of alignment parts (8) != number of exons (6) for NM_001134624.1
WARN Number of alignment parts (9) != number of exons (5) for NM_001109338.1
WARN Number of alignment parts (21) != number of exons (16) for NM_001134961.1
WARN Number of alignment parts (46) != number of exons (30) for NM_001168559.1
WARN Number of alignment parts (16) != number of exons (11) for NM_001271438.1
WARN Number of alignment parts (13) != number of exons (5) for NM_173302.1
WARN Number of alignment parts (7) != number of exons (3) for NM_001271361.1
WARN Number of alignment parts (18) != number of exons (15) for NM_001170593.1
WARN Number of alignment parts (8) != number of exons (6) for NM_001085381.1
WARN Number of alignment parts (9) != number of exons (8) for NM_022666.1
WARN Number of alignment parts (9) != number of exons (4) for NM_001107753.1
WARN Number of alignment parts (6) != number of exons (3) for NM_001013918.1
WARN Number of alignment parts (3) != number of exons (2) for NM_001271404.1
WARN Number of alignment parts (31) != number of exons (15) for NM_001191562.1
WARN Number of alignment parts (6) != number of exons (31) for NM_031504.3
WARN Number of alignment parts (10) != number of exons (5) for NM_138903.1
WARN Number of alignment parts (4) != number of exons (6) for NM_001134592.1
INFO Serializing JannovarData to data/rn6_refseq.ser
INFO Serialization took 18.99 sec.
```
</details>
