### ISSUE TITLE
Translation of HGVS into VCF stalls when writing VCF file with some mutations

### ISSUE THREAD

**Issue by mmcneill123** [charite/jannovar#483]
Using jannovar v0.32 and hg38
Submitting NM_018136.4:c.1006_1008del or NM_018136.4:c.10006_10008del converts to output values. However, submitting NM_018136.4:c.1406_1408del hangs when writing to the output vcf file.  

I get the following error logging information after "Opening output VCF file..."
`Exception in thread "main" java.lang.IllegalArgumentException: Negative position
        at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:718)
        at htsjdk.samtools.reference.IndexedFastaSequenceFile.readFromPosition(IndexedFastaSequenceFile.java:148)
        at htsjdk.samtools.reference.AbstractIndexedFastaSequenceFile.getSubsequenceAt(AbstractIndexedFastaSequenceFile.java:204)
        at htsjdk.samtools.reference.IndexedFastaSequenceFile.getSubsequenceAt(IndexedFastaSequenceFile.java:49)
        at de.charite.compbio.jannovar.vardbs.base.VariantNormalizer.shiftLeft(VariantNormalizer.java:84)
        at de.charite.compbio.jannovar.vardbs.base.VariantNormalizer.normalizeInsertion(VariantNormalizer.java:63)
        at de.charite.compbio.jannovar.cmd.hgvs_to_vcf.ProjectTranscriptToChromosome.writeVariant(ProjectTranscriptToChromosome.java:209)
        at de.charite.compbio.jannovar.cmd.hgvs_to_vcf.ProjectTranscriptToChromosome.processFile(ProjectTranscriptToChromosome.java:174)
        at de.charite.compbio.jannovar.cmd.hgvs_to_vcf.ProjectTranscriptToChromosome.run(ProjectTranscriptToChromosome.java:77)
        at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:67)`

Can you help identify and fix this issue?

**Comment by kegunder** [comment]
Here's a patch that fixes this issue (in my case)...  please review:

Index: jannovar-htsjdk/src/main/java/de/charite/compbio/jannovar/hgvs/bridge/NucleotideChangeToGenomeVariantTranslationImplBase.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- jannovar-htsjdk/src/main/java/de/charite/compbio/jannovar/hgvs/bridge/NucleotideChangeToGenomeVariantTranslationImplBase.java	(revision 2c90181c4e9bb25d8ca6233c939614537527fda6)
+++ jannovar-htsjdk/src/main/java/de/charite/compbio/jannovar/hgvs/bridge/NucleotideChangeToGenomeVariantTranslationImplBase.java	(date 1579722986860)
@@ -41,7 +41,7 @@
 	protected String getGenomeSeq(Strand strand, GenomeInterval gItv) {
 		String result = seqExtractor.load(gItv.withStrand(Strand.FWD));
 		if (strand == Strand.REV)
-			result = DNAUtils.reverseComplement(result);
+			result = DNAUtils.reverseComplement(result.toUpperCase());
 		return result.toUpperCase();
 	}

**Comment by holtgrewe** [comment]
@mmcneill123 thanks for reporting this and @kegunder thanks for the fix. I'll have a look.

**Comment by holtgrewe** [comment]
Hi, this works for me with the current `master` (will become v0.36, despite the currently incorrect version in `pom.xml`). Please reopen if the problem persists.

```
# java -jar jannovar-cli/target/jannovar-cli-0.35-SNAPSHOT.jar hgvs-to-vcf -d ../jannovar-data-0.34/hg38_refseq.ser -o out.vcf -i input.txt -r /fast/projects/cubit/current/static_data/reference/GRCh38/hs38/hs38.fa
Options
ProjectTranscriptToChromosomeOptions [pathInputText=input.txt, pathOutputVCF=out.vcf, pathReferenceFASTA=/fast/projects/cubit/current/static_data/reference/GRCh38/hs38/hs38.fa, toString()=JannovarAnnotationOptions [useThreeLetterAminoAcidCode=false, nt3PrimeShifting=false, showAll=false, databaseFilePath=../jannovar-data-0.34/hg38_refseq.ser, toString()=JannovarBaseOptions [reportProgress=true, httpProxy=null, httpsProxy=null, ftpProxy=null, verbosity=1]]]
Loading database file...
INFO Deserializing JannovarData from ../jannovar-data-0.34/hg38_refseq.ser
INFO Deserialization took 8.54 sec.
Loading FASTA index...
Opening output VCF file...
NM_018136.4:c.1006_1008del => NucleotideVariant [seqType=CODING_DNA, refID=NM_018136, proteinID=null, transcriptVersion=4] => 1:g.197143244_197143246delTGT
NM_018136.4:c.10006_10008del => NucleotideVariant [seqType=CODING_DNA, refID=NM_018136, proteinID=null, transcriptVersion=4] => 1:g.197088409_197088411delAAC
NM_018136.4:c.1406_1408del => NucleotideVariant [seqType=CODING_DNA, refID=NM_018136, proteinID=null, transcriptVersion=4] => 1:g.197142844_197142846delGAT
```

**Comment by holtgrewe** [comment]
OK, also works in current `develop`.
