### ISSUE TITLE
Download/processing of hg19/* fails

### ISSUE THREAD

**Issue by stolpeo** [charite/jannovar#487]
The following downloads fail during building the ReferenceDictionary:

```
Downloading/parsing for data source "hg19/ucsc"
Downloading/parsing for data source "hg19/ensembl"
Downloading/parsing for data source "hg19/refseq"
Downloading/parsing for data source "hg19/refseq_curated"
Downloading/parsing for data source "hg19/refseq_interim"
Downloading/parsing for data source "hg19/refseq_interim_curated"
```

All throw the same error message:

```
INFO Building ReferenceDictionary...
Exception in thread "main" java.lang.IllegalArgumentException: Multiple entries with same key: 25=16569 and 25=16571
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:190)
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:109)
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:95)
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:357)
        at de.charite.compbio.jannovar.data.ReferenceDictionaryBuilder.build(ReferenceDictionaryBuilder.java:115)
        at de.charite.compbio.jannovar.impl.parse.ReferenceDictParser.parse(ReferenceDictParser.java:127)
        at de.charite.compbio.jannovar.datasource.JannovarDataFactory.build(JannovarDataFactory.java:101)
        at de.charite.compbio.jannovar.cmd.download.DownloadCommand.run(DownloadCommand.java:43)
        at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:67)
```

**Comment by visze** [comment]
fixed by #488
