### ISSUE TITLE
unable to download Mouse transcript databases

### ISSUE THREAD

**Issue by myeelaw** [charite/jannovar#492]
Here are the command line used and output:

java -jar jannovar-cli-0.34.jar download -d mm10/refseq
Options
JannovarDownloadOptions [downloadDir=data, getDataSourceFiles()=[bundle:///default_sources.ini], isReportProgress()=true, getHttpProxy()=null, getHttpsProxy()=null, getFtpProxy()=null, geneIdentifiers=[], outputFile=]
Downloading/parsing for data source "mm10/refseq"
INFO Downloading data...
INFO Downloading https://ftp.ncbi.nlm.nih.gov/genomes/M_musculus/GFF/ref_GRCm38.p6_top_level.gff3.gz
INFO Creating directory data/mm10/refseq
ERROR: ERROR: Problem downloading file: https://ftp.ncbi.nlm.nih.gov/genomes/M_musculus/GFF/ref_GRCm38.p6_top_level.gff3.gz
de.charite.compbio.jannovar.datasource.FileDownloadException: ERROR: Problem downloading file: https://ftp.ncbi.nlm.nih.gov/genomes/M_musculus/GFF/ref_GRCm38.p6_top_level.gff3.gz
	at de.charite.compbio.jannovar.datasource.FileDownloader.copyURLToFileThroughURL(FileDownloader.java:253)
	at de.charite.compbio.jannovar.datasource.FileDownloader.copyURLToFile(FileDownloader.java:79)
	at de.charite.compbio.jannovar.datasource.JannovarDataFactory.build(JannovarDataFactory.java:83)
	at de.charite.compbio.jannovar.cmd.download.DownloadCommand.run(DownloadCommand.java:43)
	at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:67)

I believe the links are broken...

**Comment by holtgrewe** [comment]
Should be fixed by pre-built databases. Otherwise, please report in a new issue.
