### ISSUE TITLE
Problems with projection of dbSNP variants and RefSeq for hg38

### ISSUE THREAD

**Issue by holtgrewe** [charite/jannovar#524]
**Describe the bug**
Jannovar crashes for some variants for hg38 and RefSeq. This is the collection ticket for dbSNP positions.

**To Reproduce**
Run with Jannovar 0.36-SNAPSHOT and data release candidate.

**Expected behavior**
Jannovar should not crash as all errors should be properly handled and annotated.

**Additional context**
N/A

**Comment by holtgrewe** [comment]
First one that was found:

```
java -jar jannovar/jannovar-cli-0.36-SNAPSHOT.jar annotate-vcf -d jannovar/refseq_109_hg38.ser -i dbsnp-b150-GRCh38.vcf.gz -o out/refseq_109_hg38.ser.d/dbsnp-b150-GRCh38.vcf.gz --ref-fasta /fast/projects/cubit/current/static_data/reference/GRCh38/hs38/hs38.fa --interval chr1:150574533-248956422
Options
JannovarAnnotateVCFOptions [escapeAnnField=true, pathInputVCF=dbsnp-b150-GRCh38.vcf.gz, interval=chr1:150574533-248956422, pathOutputVCF=out/refseq_109_hg38.ser.d/dbsnp-b150-GRCh38.vcf.gz, pathVCFDBSNP=null, prefixDBSNP=DBSNP_, pathFASTARef=/fast/projects/cubit/current/static_data/reference/GRCh38/hs38/hs38.fa, pathVCFExac=null, prefixExac=EXAC_, pathVCFGnomadExomes=null, prefixGnomadExomes=GNOMAD_EXOMES_, pathVCFGnomadGenomes=null, prefixGnomadGenomes=GNOMAD_GENOMES_, pathVCFUK10K=null, prefixUK10K=UK10K_, pathThousandGenomes=null, prefixThousandGenomes=G1K_, pathClinVar=null, prefixClinVar=CLINVAR_, pathCosmic=null, prefixCosmic=COSMIC_, pathPedFile=null, annotateAsSingletonPedigree=false, useThresholdFilters=false, useAdvancedPedigreeFilters=false, threshFiltMinGtCovHet=8, threshFiltMinGtCovHomAlt=4, threshFiltMaxCov=10000, threshFiltMinGtGq=20, threshFiltMinGtAafHet=0.2, threshFiltMaxGtAafHet=0.8, threshFiltMinGtAafHomAlt=0.7, threshFiltMaxGtAafHomRef=0.3, threshFiltMaxExacHomAlt=20, threshFiltMaxThousandGenomesHomAlt=10, threshFiltMaxAlleleFrequencyAd=0.01, threshFiltMaxAlleleFrequencyAr=0.01, offTargetFilterEnabled=false, offTargetFilterUtrIsOffTarget=false, offTargetFilterIntronicSpliceIsOffTarget=false, oneParentGtFilteredFiltersAffected=false, inheritanceAnnoUseFilters=false, useParentGtIsFiltered=true, threshDeNovoParentAd2=1, bedAnnotationOptions=[], dbNsfpColContig=1, dbNsfpColPosition=2, prefixDbNsfp=DBNSFP_, pathDbNsfp=null, columnsDbNsfp=[], tsvAnnotationOptions=[], vcfAnnotationOptions=[]]
Deserializing transcripts...
INFO Deserializing JannovarData from jannovar/refseq_109_hg38.ser
INFO Deserialization took 9.83 sec.
Progress reporting does not work because VCF file is missing the contig lines in the header.
Annotating VCF...
Will read interval chr1:150574533-248956422     +       .
Exception in thread "main" java.lang.Error: Bug: problem with projection! (AnnotationLocation{transcript=NM_001197320.1(1:g.150574551_150579738), rankType=EXON, rank=3, totalRank=4, txLocation=NM_001197320.1:n.3629_3629})
        at de.charite.compbio.jannovar.annotation.VCFAnnotationData.setAnnoLoc(VCFAnnotationData.java:116)
        at de.charite.compbio.jannovar.annotation.Annotation.toVCFAnnoString(Annotation.java:287)
        at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.applyAnnotations(VariantContextAnnotator.java:400)
        at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.dispatchAnnotateVariantContext(VariantContextAnnotator.java:337)
        at de.charite.compbio.jannovar.htsjdk.VariantContextAnnotator.annotateVariantContext(VariantContextAnnotator.java:296)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:490)
        at de.charite.compbio.jannovar.cmd.annotate_vcf.AnnotateVCFCommand.run(AnnotateVCFCommand.java:411)
        at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:74)
Caused by: de.charite.compbio.jannovar.reference.ProjectionException: Invalid transcript sequence position 3628
        at de.charite.compbio.jannovar.reference.TranscriptProjectionDecorator.transcriptToGenomePos(TranscriptProjectionDecorator.java:170)
        at de.charite.compbio.jannovar.annotation.VCFAnnotationData.setAnnoLoc(VCFAnnotationData.java:113)
        ... 15 more
```

**Comment by holtgrewe** [comment]
OK, current #525 runs through on dbSNP which previously failed. I'd say that's good enough for a release.
