### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by leemdi** [charite/jannovar#567]
Platform:  CentOS Linux Version 7
java -version:  openjdk version "1.8.0_322"

**Is Java 1.8 supported?**

java -jar jannovar-cli/target/jannovar-cli-0.42-SNAPSHOT.jar annotate-pos -d refseq_curated_139_mm39.ser --3-letter-amino-acids --show-all -c 'chr6:716554934C>T'

Options
JannovarAnnotatePosOptions [genomicChanges=[chr6:716554934C>T], toString()=JannovarAnnotationOptions [useThreeLetterAminoAcidCode=true, nt3PrimeShifting=true, showAll=true, databaseFilePath=refseq_curated_139_mm39.ser, toString()=JannovarBaseOptions [reportProgress=true, httpProxy=null, httpsProxy=null, ftpProxy=null, verbosity=1]]]
Deserializing transcripts...
INFO Deserializing JannovarData from refseq_curated_139_mm39.ser
INFO Deserialization took 0.04 sec.
#change effect  hgvs_annotation messages
Exception in thread "main" java.lang.NullPointerException
        at de.charite.compbio.jannovar.cmd.annotate_pos.AnnotatePositionCommand.parseGenomeChange(AnnotatePositionCommand.java:100)
        at de.charite.compbio.jannovar.cmd.annotate_pos.AnnotatePositionCommand.run(AnnotatePositionCommand.java:60)
        at de.charite.compbio.jannovar.Jannovar.main(Jannovar.java:74)

Thanks.
Lori

**Comment by leemdi** [comment]
https://zenodo.org/record/5410367/files/refseq_139_mm39.ser?download=1

this file is bad

please help.  we cannot use your product if we don't have a good file.
