### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by dawe** [charite/jannovar#6]
I've just downloaded the .jar file from main site. At the first test run I got:

```bash
$ java -jar Jannovar.jar -D data/ucsc_hg19.ser -V MyVCF.vcf
shift (C - C)
shift (C - C)
shift (C - C)
shift (C - C)
shift (C - C)
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 5
        at java.lang.String.charAt(String.java:658)
        at jannovar.annotation.InsertionAnnotation.getAnnotation(InsertionAnnotation.java:217)
        at jannovar.reference.Chromosome.annotateExonicVariants(Chromosome.java:723)
        at jannovar.reference.Chromosome.getPlusStrandAnnotation(Chromosome.java:434)
        at jannovar.reference.Chromosome.getAnnotationList(Chromosome.java:169)
        at jannovar.Jannovar.annotateVCFLine(Jannovar.java:378)
        at jannovar.Jannovar.outputAnnotatedVCF(Jannovar.java:485)
        at jannovar.Jannovar.annotateVCF(Jannovar.java:600)
        at jannovar.Jannovar.main(Jannovar.java:250)```
```

**Comment by holtgrewe** [comment]
Please try again with version 0.12 if the problem persists and open again.
