### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: Key  found in VariantContext field INFO at 1:949696 but this key isn't defined in the VCFHeader.  We require all VCFs to have complete VCF headers by default.

### ISSUE THREAD

**Issue by leipzig** [charite/jannovar#70]
```
##fileformat=VCFv4.1
##source=HGMD_PRO_2013.4
##version=0.1_beta
##reference=GRCh37
##fileDate=20131215
##comment="REF and ALT sequences are both on forward strand of reference assembly"
##INFO=<ID=CLASS,Number=1,Type=String,Description="Mutation Category, https://portal.biobase-international.com/hgmd/pro/global.php#cats ">
##INFO=<ID=MUT,Number=1,Type=String,Description="HGMD mutant allele">
##INFO=<ID=GENE,Number=1,Type=String,Description="Gene symbol">
##INFO=<ID=STRAND,Number=1,Type=String,Description="Gene strand">
##INFO=<ID=DNA,Number=1,Type=String,Description="DNA annotation">
##INFO=<ID=PROT,Number=1,Type=String,Description="Protein annotation">
##INFO=<ID=DB,Number=1,Type=String,Description="dbSNP identifier, build 137">
##INFO=<ID=PHEN,Number=1,Type=String,Description="HGMD primary phenotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
1	949696	CI128669	C	CG	.	.	CLASS=DM;MUT=ALT;GENE=ISG15;STRAND=+;DNA=NM_005101.3:c.339dupG;
```

```
java -jar jannovar-cli-0.11/jannovar-cli-0.11.jar annotate -a jannovar-cli-0.11/data/hg19_refseq.ser HGMD_PRO_2013_4.nophen.vcf 
Options
dataFile: jannovar-cli-0.11/data/hg19_refseq.ser
changes: []
showAll: true
jannovarFormat: false
Deserializing transcripts...
Deserialization took 6.25 sec.
Annotating VCF...
Exception in thread "main" java.lang.IllegalStateException: Key  found in VariantContext field INFO at 1:949696 but this key isn't defined in the VCFHeader.  We require all VCFs to have complete VCF headers by default.
	at htsjdk.variant.vcf.VCFEncoder.fieldIsMissingFromHeaderError(VCFEncoder.java:173)
	at htsjdk.variant.vcf.VCFEncoder.encode(VCFEncoder.java:112)
	at htsjdk.variant.variantcontext.writer.VCFWriter.add(VCFWriter.java:214)
	at jannovar.cmd.annotate_vcf.AnnotatedVCFWriter.put(AnnotatedVCFWriter.java:188)
	at jannovar.cmd.annotate_vcf.AnnotateVCFCommand.run(AnnotateVCFCommand.java:58)
	at jannovar.Jannovar.main(Jannovar.java:101)
```

**Comment by holtgrewe** [comment]
Thank you for reporting this, I will try to release and upload 0.12 version today that will include the fix.
