### ISSUE TITLE
NullPointerException thrown when certain deletion annotations encountered

### ISSUE THREAD

**Issue by buske** [charite/jannovar#8]
I'm getting a NullPointerException from a number of deletion annotations, including: `chr13:c.113201891TCGCGCGTGGGAAAG>-`

```
java.lang.NullPointerException
	at jannovar.reference.Translator.translateDNA(Translator.java:54) ~[jannovar-0.8-SNAPSHOT.jar:?]
	at jannovar.annotation.DeletionAnnotation.getMultinucleotideDeletionAnnotation(DeletionAnnotation.java:253) ~[jannovar-0.8-SNAPSHOT.jar:?]
	at jannovar.reference.Chromosome.annotateExonicVariants(Chromosome.java:771) ~[jannovar-0.8-SNAPSHOT.jar:?]
	at jannovar.reference.Chromosome.getMinusStrandAnnotation(Chromosome.java:650) ~[jannovar-0.8-SNAPSHOT.jar:?]
	at jannovar.reference.Chromosome.getAnnotationList(Chromosome.java:172) ~[jannovar-0.8-SNAPSHOT.jar:?]
	at [... originally called from Exomiser]
```

**Comment by holtgrewe** [comment]
Please try again with version 0.12 if the problem persists and open again.
